doajtest/unit/test_models.py, portality/models/journal.py, portality/models/suggestion.py
This is implemented at the save() level, so any operation which causes the owner to change will cause the related journal/application to be updated.  It comes that the cost of an additional query to the index, and the possibility of an additional write (if the owner needs to be synchronised).
=> ensure that owners are synchronised between journals and suggestions

doajtest/unit/test_reapplication.py, portality/models/suggestion.py
works by loading the journal being overwritten and nabbing its create date, before overwriting it.
Also with test.
=> when a suggestion overwrites an existing journal, preserve the create date

doajtest/unit/test_reapplication.py, portality/models/journal.py, portality/models/suggestion.py
I was /always/ copying over the history from journal to replacement, even if it was None, resulting an an erroneous None in the history field, which was then in turn causing a NoneType error further down the chain.
Both the write of the history and a None check on read have now been implemented, which prevents this at both ends of the problem.
=> fix nonetype bug in history read

portality/core.py
This minor change is key for the migration from es 0.x to ex 1.x - it changes the way that mappings are created at application initialisation.  Other than that DOAJ appears to operate fine under 1.4.2, and when we upgrade to fv2 we'll iron out any minor niggles.
My suggestion is that we merge this change to develop asap, and then carry on building on top of ES 1.4.  This will initially break the test server, as it is running 0.9, so there will be a period when builds and test are not operational.  I'll open some issues to cover that shortly.
=> tweaks to core to initialise correctly with es14

portality/templates/_js_includes.html, portality/templates/doaj/subjects.html, portality/templates/header.html, portality/view/doaj.py
I've gone for a jstree based approach, since once I made a start trying to lay out the subjects it was clear that the varying depths of the tree at different points would make a static layout prohibitively difficult.
Instead the solution is more javascript oriented, and reactive to the user.  Hopefully it is the right kind of thing.
=> add first draft of subject browser

portality/models/article.py, portality/view/doaj.py
No need for ToC index now. But still uses the JournalVolumeToc model. If ToC is not needed anywhere else then that model should be simplified down to a shell model as there will be no index to send data to.
=> updated doaj view blueprint so that toc calls Articles directly

doajtest/unit/test_oaipmh.py, portality/datasets.py, portality/models/article.py, portality/models/bibjson.py, portality/settings.py, portality/templates/doaj/doajArticles_oai_namespace.html, portality/templates/doaj/features.html, portality/view/doaj.py, portality/view/oaipmh.py
Issues #180 and #542 
Adds new format. Tested locally and all the data seems to correspond to the OAI_DC format exactly, except in the places where it should differ (namespace, core element being named doajArticle rather than dc, and of course most fields in the metadata element - where the formats actually differ).
Also adds a small webpage which will eventually be served at the namespace URL http://doaj.org/features/oai_doaj/1.0/ .
Also makes list of metadata formats different for different OAI endpoints. It should be very little effort to add more endpoints and formats in the future with the new config this introduces.
=> OAI new doaj article format

README.md, doajtest/unit/test_api_account.py, portality/app.py, portality/authorise.py, portality/core.py, portality/dao.py, portality/decorators.py, portality/migrate/api_v1/README.md, portality/migrate/api_v1/api_auth.json, portality/models/account.py, portality/settings.py, portality/upgrade.py, portality/view/account.py, portality/view/admin.py, portality/view/doaj.py, portality/view/doajservices.py, portality/view/editor.py, portality/view/publisher.py
for API issue #734:
* added new roles 'user' (top level) and 'api' to allow api access
* added 'api_key' to Account model
* updated account creation to give api role and set api_key by default
* added new decorator for checking requests have active api_key
* updated readme to include new fields in data model
* new tests for api account
* refactored decorators out of portality.core to avoid circular import (including ssl_required etc)
* tidied up some imports
* updated an outdated function call in core.py
=> User / authentication 

portality/app.py, portality/static/doaj/css/doaj_api.css, portality/templates/doaj/api_docs.html, portality/view/api_v1.py
Overall prep of discovery API docs for final release. Only missing thing is applications schema and sort options. Journals and articles routes should be complete and you should not need to refer to github in order to perform a search - all info should be there.
Would be great if you have the time to have a play with the 2 public endpoints @richard-jones @Steven-Eardley @Nimphal . Paging, sorting, searching, shorthand fields were my stops on the happy api bus.
Also overall how does it look / feel? There is now a screenful of text before it gets to the examples - however you can link to a specific live route demo by just opening it (the URL will change and if you share that, it'll scroll past the text). My biggest question is should the text go somehow below the live demos, or is it OK as …
=> prepare final version of discovery API docs sans applications

doajtest/unit/test_api_account.py, portality/api/v1/__init__.py, portality/api/v1/crud/__init__.py, portality/api/v1/crud/applications.py, portality/api/v1/crud/articles.py, portality/api/v1/crud/common.py, portality/api/v1/crud/journals.py, portality/decorators.py, portality/view/api_v1.py
This contains the CRUD API foundation ref #754 
Some notes have been added as well for @Nimphal and @bg280 to start on.
The overall structure is one of composition: we have a package for the whole CRUD API, and inside that package we have an ApplicationsCrudApi, an ArticleCrudApi and a JournalCrudApi. The ```CrudApi``` which is eventually used by the view and exposed at the top-level (portality.api.v1) simply inherits from those 3 APIs, gaining all their methods in the process.
The whole thing enables:
1. adding new types to CRUD very easily
2. keeping code separate for applications, articles and journals - if we had one CrudApi class it'd be hard to edit and git would also complain a lot when multiple people worked on the one file. And it'd be like 1500 lines long by the end.
3. …
=> add CRUD API foundation together with journal route notes

portality/api/v1/__init__.py, portality/api/v1/crud/__init__.py, portality/api/v1/crud/applications.py, portality/api/v1/crud/articles.py, portality/api/v1/crud/common.py, portality/api/v1/crud/journals.py, portality/view/api_v1.py
No tests to write/change yet. This changes the CRUD tech design so it fits with what we discussed in the meeting - now you can import an ApplicationsCrudApi, etc. from portality.api.v1 .
=> modify CRUD api internals to now expose 3 CRUD API-s with a common parent

doajtest/fixtures/applications.py, doajtest/fixtures/journals.py, doajtest/unit/test_api_crud_application.py, doajtest/unit/test_api_dataobj.py, portality/api/v1/__init__.py, portality/api/v1/common.py, portality/api/v1/crud/README.md, portality/api/v1/crud/applications.py, portality/api/v1/data_objects/__init__.py, portality/api/v1/data_objects/application.py, portality/api/v1/data_objects/journal.py, portality/datasets.py, portality/lib/dataobj.py, portality/models/journal.py, portality/view/api_v1.py
This provides the following:
* A new data object based on the previous iteration, but with more features
* Revised model objects and tests for journal/vanilla data object
* The Create portion of the Application CRUD API
* Some additions to the api common library which may be shared over all object types
* a README which outlines the API interactions planned for the Applications
It isn't the final Application CRUD but because of the new data object, and the overall pattern demonstrated around Application Create I think it is useful to merge this now.  It also has common code that other CRUD endpoints will want to make use of.
=> New data object and Application Create API

doajtest/fixtures/applications.py, doajtest/unit/test_api_crud_application.py, portality/api/v1/crud/applications.py, portality/api/v1/data_objects/application.py, portality/datasets.py, portality/formcontext/choices.py, portality/lib/dataobj.py
Thought it would be useful to make another PR, as I've now done a full treatment of the validation requirements for the application model, and this will be useful in the implementation of the journal crud.
Note the addition of custom coerce functions in the constructor, which use a newly created string_canonicalise dataobj coerce routine, giving us parity with the behaviour of the submission form.
=> Complete treatment of application object validation

portality/static/doaj/js/available_facetviews/admin.applications.facetview.js, portality/static/doaj/js/available_facetviews/admin.editorgroups.facetview.js, portality/static/doaj/js/available_facetviews/admin.journalarticle.facetview.js, portality/static/doaj/js/available_facetviews/admin.journals.facetview.js, portality/static/doaj/js/available_facetviews/associate.applications.facetview.js, portality/static/doaj/js/available_facetviews/associate.journals.facetview.js, portality/static/doaj/js/available_facetviews/editor.groupapplications.facetview.js, portality/static/doaj/js/available_facetviews/editor.groupjournals.facetview.js, portality/static/doaj/js/available_facetviews/public.journalarticle.facetview.js, portality/static/doaj/js/available_facetviews/publisher.journals.facetview.js, portality/static/doaj/js/available_facetviews/publisher.reapplications.facetview.js, portality/static/doaj/js/available_facetviews/users.facetview.js, portality/static/doaj/js/doaj.facetview.theme.js
For #854 
There are many ways I could've done this including just removing .icon-white and .icon-remove with Javascript on page load, and then replacing with .fa .fa-remove . But that feels hackier, I think the HTML should contain the intent (otherwise as a dev I will one day wonder why the hell are my bootstrap icons coloured when that's impossible and I don't seem to be using FontAwesome ones - the override is too easy to miss).
I wanted to do it the right way which to me seems to be to use the callback functionality and just render custom filters, identical in every way except the remove icon.
=> [hotfix] Fix invisible close button on filters

doajtest/fixtures/article.py, doajtest/fixtures/journals.py, doajtest/unit/test_api_crud_journal.py, doajtest/unit/test_api_dataobj.py, portality/api/v1/crud/applications.py, portality/api/v1/crud/journals.py, portality/api/v1/data_objects/__init__.py, portality/api/v1/data_objects/application.py, portality/api/v1/data_objects/common_journal_application.py, portality/api/v1/data_objects/journal.py, portality/lib/dataobj.py, portality/view/api_v1.py
Finally! @Steven-Eardley @richard-jones 
Important things:
1. Introduce journals, duh. Tests, api class, view func.
EDIT: I've taken the Application struct that Richard wrote (since it has more type casts) and tacked on fields like oa_end that only journals have. Also journals and applications now expose both subjects and keywords.
2. Refactor applications a bit to use common logic with journals. Had to make a common Outgoing object since it was just the best way to share the logic I could come up with, and it allows more sharing in the future. Sorry about the name of the common object, I thought for 5 min but couldn't come up with "what's the parent of journal and application conceptually". Suggestions very welcome.
3. Introduce parity between incoming and outgoing applications with …
=> add journal retrieval to crud

portality/settings.py, portality/templates/api/v1/api_docs.html
For the harvester project, but may be suitable to roll out along with the API anyway?  See #932
=> add username substitution to journal api, and add documentation

portality/decorators.py, portality/settings.py, portality/tasks/__init__.py, portality/tasks/journal_in_out_doaj.py, portality/view/account.py, portality/view/admin.py, portality/view/doaj.py, portality/view/doajservices.py, portality/view/editor.py, portality/view/publisher.py, setup.py
#1126 
There we are!
Code needs better organisation (like the location of the `huey` object), but this is a good example and start.
Get redis to run. Install via apt-get for now if you want then `sudo service redis-server start`. I am actually using docker, so I can use the newest version of redis, which production will also use. I think we should all do that. I'll tell you how tomorrow (but basically, 
1. install docker from its PPA repo, not ubuntu main repos - follow its tutorial online; 
2. `sudo docker run -p 127.0.0.1:6400:6379 --name doaj-redis -d redis:3.2.5` ; 
3. `sudo docker stop/start doaj-redis` and `sudo docker ps` for management; 
4. set HUEY_REDIS_PORT=6400 in your dev.cfg
).
pip install -r requirements.txt to get huey and redis-py.
Then run
huey_consumer.py …
=> replace journal activate/deactivate tasks with huey tasks + necessary refactors

doajtest/unit/test_task_article_bulk_delete.py, doajtest/unit/test_util.py, portality/dao.py, portality/static/doaj/js/available_facetviews/admin.journalarticle.facetview.js, portality/tasks/article_bulk_delete.py, portality/tasks/consumer.py, portality/util.py, portality/view/admin.py
Fully working, tested. Back-end only.
Remaining:
- on the UI, disable the bulk job Submit button if the Delete option is selected and if the user has not yet selected an option in the _type facet.
- make sure the UI takes the option selected in the _type facet into account when submitting bulk delete jobs. There are 2 URLs in admin.py, not one.
=> bulk article delete; no UI yet

portality/models/suggestion.py
HOTFIX
Modify application struct for index.publisher field, omitted by error in the previous hotfix.
After this has been applied, the original migrate script needs to be run again:
python portality/upgrade.py -u portality/migrate/1196_publisher_struct/publisher_struct.json
=> HOTFIX modify struct for publisher in index for applications

deploy/deploy-gateway.sh
supervisord configs are as of very recently stored as (e.g.) `/deploy/supervisor/test/doaj-test.conf` where `/` denotes the DOAJ repo root. EDIT: currently, the script in this PR links them to `/deploy/supervisor/doaj-test.conf` which is the old location.
On the server, they are indeed placed in (e.g.) `/home/cloo/repl/test/supervisor/conf.d/` so the 2nd argument to `ln` is correct.
Looks like I used the correct subdirectory for the section below, `prep sym links for the background app server`, but forgot to change the subdir in the web app's section.
=> [hotfix] fix application supervisor link

portality/migrate/1303_nonexistent_editors_assigned/nonexistent_editors_assigned.py, portality/migrate/1303_nonexistent_editors_assigned/readme.md
#1303 
Data clean. Can be rerun as necessary. **Should** be rerun once we implement a bit in the "delete user" feature which finds all the users' assigned applications and blanks them out of the editor field.
=> add migration to blank out nonexistent editor usernames

portality/scripts/inconsistent_journal_prov_application.py
This makes the reporting on possible failed reapplications more accurate, so the results are meaningful
=> extend reporting to properly report on possible failed reapplications

doajtest/fixtures/dois.py, doajtest/fixtures/issns.py, doajtest/unit/test_regexes.py, portality/view/forms.py
based on contributions by @katrinleinweber 
I've made this a string literal to improve readability (doing away with the ```\\```), and removed duplicated protocol portions. Finally, escaped an extra ```.``` which allowed us to accept e.g. ```dx.doiZorg``` since it's a wildcard.
=> Simplified and updated the DOI regex

portality/scripts/articles_invalid_url.py
Connects to: https://github.com/DOAJ/doajPM/issues/2038
Solution for: https://github.com/DOAJ/doajPM/issues/2038#issuecomment-518259336 (p. 2)
In the portality/scripts you can find articles_invalid_url.py script. Running that on our live server will give us info about which articles have invalid URL. In the output file, there is Article id, Article title, URL and info if the article is in DOAJ or not (articles in doaj are listed in the first place).
=> Script to find malformed urls

doajtest/unit/test_formcontext_emails.py, portality/templates/publisher/metadata.html
On the upload metadata form for a publisher it is possible to remove all the authors' fields. Unfortunately then the button "Add More Authors" doesn't work. Because at least one Author is required I think it is a good idea to just prevent the user from removing all the fields and give him proper error if she/he tries to do so - exactly the same one as she/he would like to submit the form without the authors.
=> prevent removing last author div from metadata form

doajtest/unit/test_openurl.py, portality/view/openurl.py
This test suit checks the old and new versions of OpenURL requests. Results in 88% of coverage on view/openurl.py and 78% on models/openurl.py.
Additionally, this PR fixes error found (thank you @Steven-Eardley for your help)
=> OpenURL web endpoint tests

portality/formcontext/formcontext.py
Fixes: https://github.com/DOAJ/doajPM/issues/2206
URL fields' full content descriptions are clickable URL and open in a new tab.
=> make url descriptions clickable

doajtest/fixtures/journals.py, doajtest/unit/test_api_dataobj.py, portality/api/v1/data_objects/journal.py
This PR does not require any URL for outgoing journals - unicode is accepted. That way even if url is not correct the journal metadata still will be displayed.
#Connects to: https://github.com/DOAJ/doajPM/issues/2268#issuecomment-579190600
=> Relax requirements for outgoing journal struct

doajtest/fixtures/article.py, doajtest/fixtures/v2/journals.py, portality/api/v2/data_objects/application.py, portality/api/v2/data_objects/article.py, portality/api/v2/data_objects/journal.py, portality/dao.py, portality/migrate/20200423_af_redesign/migrate.py, portality/models/background.py, portality/models/harvester.py, portality/models/provenance.py, portality/models/search.py, portality/models/v2/shared_structs.py, portality/static/js/edges/admin.journalarticle.edge.js, portality/static/js/edges/public.journalarticle.edge.js
adds `es_type` to all models, which functionally replaces `_type`.
I've tested this migration from old to new index-per-type connection, but in theory it should also migrate to new models without ipt too. Edges have been updated too.
=> Feature/af redesign  ipt add es type

portality/settings.py
Just a nice to have:
Setting the Redis and Elasticsearch host/port settings via environment variables helps with dockerized setups.
The alternative is to set these values via the environment specific `.cfg` files, but we find this a bit cumbersome for our use case (Throw-away environments for a continuous integration pipeline).
=> Adds support for env vars when setting default service hosts

cms/sass/layout/_secondary-nav.scss
Need to test it out with various people, not sure if this is the right approach. The big downside to doing this is that, though it allows people to "scroll" down the menu on mobile, it will also require them to go back to the top of the page to tap the "MENU" item to close it again. This isn’t clear, nor intuitive. 
We could ensure that the MENU button changes to "CLOSE" and the hamburger icon to an X, but it requires a minor change in the JS. 
See DOAJ/doajPM#3003
=> Allow scrolling in menu on mobile

cms/sass/layout/_editorial-panel.scss, portality/static/js/formulaic.js
https://github.com/DOAJ/doajPM/issues/2904#issuecomment-998242478
@richard-jones simple js change.
@sssoz not sure whether that's what was meant by "close up the space", let me know if not. Also - I couldn't find a good place to add the css (text area has in general margin-bottom: 0.75 so to close up the space I just added -0.75 to the "view note" link). Could you move the inline style to some better place? Or maybe it can stay like this?
=> Move view note link and minimize the margin

portality/templates/layouts/sidenav.html
`.page-content` should accompany `.container` class on `<main>`
Otherwise, the dropdown menu isn’t clickable on hover!
See DOAJ/doajPM#3264
=> Ensure all header nav dropdowns don’t disappear when hovering above them 

doajtest/helpers.py, doajtest/unit/test_bll_application_unreject_application.py, doajtest/unit/test_fc_maned_app_review.py, doajtest/unit/test_models.py, doajtest/unit/test_snapshot.py, doajtest/unit/test_tasks_sitemap.py
For [2727](https://github.com/DOAJ/doajPM/issues/2727)
I found following 4 testcase fail when running with `pytest -n 4`
```
cd $DOAJ_PROJ/doajtest/unit
$VENV_HOME/venv/doaj/bin/pytest -n4 --dist loadfile --full-trace --color=yes --code-highlight=yes -v  | tee /tmp/doaj_20220614_5.log
```
```
=========================== short test summary info ============================
FAILED test_fc_maned_app_review.py::TestManEdAppReview::test_02_update_request
FAILED test_models.py::TestModels::test_06_article_deletes - assert 0 == 3
FAILED test_models.py::TestModels::test_07_journal_deletes - AssertionError: ...
FAILED test_models.py::TestModels::test_08_iterate - assert 0 == 99
```
The reason of fail is they need to update same folder when parallelise
```
ArticleHistory.SAVE_BASE_DIRECTORY …
```
=> use patch_history_dir to avoid edit same dir when multiprocessing

doajtest/unit/test_openurl.py, portality/models/openurl.py, portality/view/doaj.py
Fix OpenURL query bug
[See #3339](https://github.com/DOAJ/doajPM/issues/3339)
Fixes the query and modifies the UTs so it checks the query with volume param.
This PR...
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
=> Fix OpenURL query bug

portality/static/js/dashboard.js, portality/templates/application_form/_contact.html, portality/templates/dashboard/_todo.html, portality/templates/editor/nav.html
Implemented changes requested in the following to do: https://github.com/DOAJ/doajPM/issues/3422#issue-1463035183
**I found only `ED.` in the group info section, the tag at the top of the dashboard has those words spell out. @richard-jones Am I missing something?**
**This is only about the editor dashboard, right? @richard-jones**
=> Feature/3218 editorial todo  editor  UI bits

portality/crosswalks/article_form.py
In file: article_form.py, method: form2obj, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not match with anything else. As a result, the identity check will have a logical short circuit. The first part of the test expression already tests for it. The second part is unnecessary.
I suggested that the logical operation should be reviewed.
=> Remove an unnecessary test expression

doajtest/functional/make_notifications.py, portality/bll/services/notifications.py, portality/scripts/mark_notifications_seen.py
See https://github.com/DOAJ/doajPM/issues/3437
Core method to mark notifications as seen, and a script to trigger this.
This PR...
Just run the script on test to be sure
**N/A**
**N/A**
After release run this to clean up all the old notifications
```
python portality/scripts/mark_notifications_seen.py -u 2023-01-01
```
The `-u` argument tells the script to mark all notifications "until" that date (i.e. before it) as read.  Confirm with @dommitchell the actual desired date to go in here when it is run.
**N/A**
**N/A**
**N/A**
**N/A**
=> be able to mark notifications as seen according to some criteria

cms/sass/base/_general.scss, cms/sass/components/_filters.scss, cms/sass/components/_form.scss, doajtest/testbook/public_site/public_search.yml
2nd approach, it is important to make sure that changes are applied correctly everywhere across the service (including facets and application form).
[See 3402](https://github.com/DOAJ/doajPM/issues/3402)
This PR...
* For each checklist item that has been confirmed by the Developer, check the …
=> Accessible radiobuttons and checkboxes

cms/README.md, cms/pages/about/advisory-board-council.md, cms/pages/about/ambassadors.md, cms/pages/about/volunteers.md, portality/templates-v2/public/layouts/static-page.html
* Issue: [#4002](https://github.com/DOAJ/doajPM/issues/4002)
---
This PR introduces `data` element to pages YAML front matter that indicates whether the page contains any data in `cms/data` folder in `.md` file. By setting `data: true` in appropriate .md file it is possible to add the Edit Data button to the static page.
Icon is added to:
Advisory Board Council, Ambassadors and Volunteers
This PR...
*Developers should review and confirm each of these items before requesting review*
- No deprecated methods are used
- No magic strings/numbers - all strings are in `constants` or `messages` files
- ES queries are wrapped in a Query object rather than inlined in the code
- Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
- Cleaned up commented out …
=> Restore edit data icon on static pages
