- doajtest/unit/test_reapplication.py
- portality/reapplication.py
Turns out int2base(i, 26) doesn't work that well :). I tried diagnosing but gave up after lots of print statements failed to prod my brain into inventing a solution.
The problem is
```python
while x:
digits.append(digs[x % base])
x /= base
```
Given ```40``` (or the 41st column in our 0-indexed setting a.k.a. the ```AO``` column) this will correctly identify the 2nd letter ```O```, because 40 % 26 = 14. The 15th letter in a 0-indexed list of the uppercase alphabet.
But 40 / 26 = 1. So it passes the while loop condition, as it should (we do need 2 letters). However now you're doing ```1 % 26``` in the 2nd pass, which results in ```1```, or the 2nd letter of the alphabet - ```B```. So you end up with ```BO```, not ```AO```.
Doing something like ```x = x / base - 1``` (instead of ```x /= …
```
> Fix column label generation in reapp spreadsheet error reports

- portality/view/oaipmh.py
Introduces a DateFormat object that handles the granularity and date formatting issues
> fix date granularity issue

- doajtest/unit/test_reapplication.py
- doajtest/unit/test_tick.py
- portality/models/journal.py
- portality/models/suggestion.py
ensure that continuations are handled/preserved during reapplication
recalculate the tick based on both created date and reapplication date
> continuations and the tick

- portality/models/article.py
- portality/templates/doaj/toc.html
- portality/view/doaj.py
This time moving to generation of separate issue listings and doing it on the client js side. Tested with biomed research international, which on the last version could cause a gateway error because the backend took too long to process the 2013 volume. No such errors this time.
> another update to the notoc feature

- portality/view/doaj.py
Moved redirects after continuations logic and added more comments. For #696
There is one further case that has not, I think, been considered yet. What if somebody refers to a continuation by its P-ISSN when it has an E-ISSN? Currently it will display the continuation under both URLs instead of issuing the redirect. Redirects work OK when the journal is not a continuation.
Worth redirecting to E-ISSN version of continuations too?
> [hotfix] Fix continuations

- portality/static/doaj/css/social-media-icons.css
- portality/templates/sidebar.html
> Google+ logo

- doajtest/unit/test_feed.py
- portality/settings.py
- portality/view/atom.py
@emanuil-tolev - sorry by the time I saw your other email, I'd already started this as a feature. From this point on I'll do them as hotfixes, promise!
> change atom feed crosswalks and add feed test

- portality/templates/doaj/our_sponsors.html
- portality/templates/footer.html
> Alt image attributes for sponsors

- portality/view/api_v1.py
> Public search API docs

- portality/settings.py
- portality/static/doaj/css/doaj.css
- portality/templates/account/register.html
- portality/templates/account/view.html
- portality/view/account.py
* added UI to change api key on account page for issue #734
* reverted changes for extra role 'user'
* moved some styles from account view into doaj.css
* improved account view layout
* added role chooser to admin's new account creation page.
* removed (outdated?) references to api_key in view/account.py
> UI for API key generate/retrieve

- doajtest/bootstrap.py
- doajtest/unit/test_api_errors.py
- portality/api/v1/__init__.py
- portality/api/v1/common.py
- portality/decorators.py
- portality/settings.py
- portality/view/api_v1.py
* Improved error handlers for the API project, along with tests.
* updated api_key decorator to use new exception method.
* added route to api_v1 which returns json 404 rather than HTML
* Added new setting VALID_FEATURES which lists all available features
* test boostrap will activate all features in VALID_FEATURES, so tests don't fail
> Some changes for API-specific error handlers.

- doajtest/bootstrap.py
- doajtest/unit/test_api_errors.py
- portality/api/v1/__init__.py
- portality/api/v1/common.py
- portality/decorators.py
- portality/settings.py
- portality/templates/header.html
- portality/view/api_v1.py
Make the API link public, fix API base URL to be the right one and put in a few sentences about auth which are a bit more specific and lead to the right area now.
> [hotfix] expose API and make auth information for API easier to find

- portality/templates/formcontext/assed_application_review.html
- portality/templates/formcontext/assed_journal_review.html
- portality/templates/formcontext/editor_application_review.html
- portality/templates/formcontext/editor_journal_review.html
- portality/templates/formcontext/maned_application_review.html
- portality/templates/formcontext/maned_journal_review.html
- portality/templates/formcontext/public_application_form.html
- portality/templates/formcontext/publisher_reapplication.html
> [hotfix] Renamed save buttons on forms to shoutier ones. Issue #817

- portality/static/widget/simple_search_body.html
- portality/static/widget/simple_search_body_dev.html
- portality/static/widget/simple_search_body_staging.html
- portality/static/widget/simple_search_body_test.html
- portality/static/widget/simple_search_staging.html
- portality/static/widget/simple_search_staging.js
- portality/templates/doaj/widgets.html
- portality/view/doaj.py
> Update DOAJ logo references

- portality/static/widget/simple_search.js
- portality/static/widget/simple_search_dev.js
- portality/static/widget/simple_search_staging.js
- portality/static/widget/simple_search_test.js
For #746 (the Jqeury link needs https everywhere except on develop)
> Update the downloadeble Jquery to be over https and right version

- portality/static/widget/simple_search.js
- portality/static/widget/simple_search_dev.js
- portality/static/widget/simple_search_staging.js
- portality/static/widget/simple_search_test.js
> Update the required version of jQuery

- portality/formcontext/forms.py
> Added validator for application question 31, for issue #902.

- portality/templates/doaj/widgets.html
> Update widget docs

- portality/view/doaj.py
> fix journal resolution in article page route

- portality/static/doaj/js/doaj.facetview.theme.js
- portality/static/widget/fq_widget_depends_compiled.js
env-ified the links to static resources in widget,
Added env detection to facetview theme so that the correct widget file version can be generated
#747
> Fixed toc links on widget facetview,

- portality/settings.py
- portality/view/query.py
> add filter to public search results to strip out unwanted fields

- portality/templates/doaj/features.html
just a minor documentation update, then the oai code can be released to live
> update oai changelog text

- portality/formcontext/forms.py
- portality/formcontext/validate.py
- portality/models/account.py
- portality/settings.py
#1100 
Plus a tiny bit of cleanup - some default args were empty lists (no-no), and a few unused imports.
> Add reserved system user

- doajtest/unit/test_reserved_usernames.py
- portality/view/account.py
#1100 
Oops, apologies!! We shouldn't be reducing the coverage on the codebase, but increasing it!
I forgot to commit this file to the earlier PR and didn't see.
> add missing tests and add enhancements to Create new user page

- portality/reporting.py
> HOTFIX increase aggregation size for country reporting

- doajtest/unit/test_reporting.py
- portality/reporting.py
> HOTFIX fix unicode read/write for reports, and update tests

- doajtest/unit/test_article_cleanup_sync.py
Increasing confidence in article cleanup script for issue #1183
> Improved tests for article cleanup script

- portality/formcontext/fields.py
> fix visual bug on app form

- portality/static/doaj/js/available_facetviews/admin.editorgroups.facetview.js
> Added .exact to fix editor group search sort. 

- doajtest/unit/test_task_article_bulk_delete.py
- doajtest/unit/test_task_journal_bulk_delete.py
- doajtest/unit/test_util.py
- portality/dao.py
- portality/static/doaj/js/available_facetviews/admin.journalarticle.facetview.js
- portality/tasks/article_bulk_delete.py
- portality/tasks/consumer.py
- portality/tasks/journal_bulk_delete.py
- portality/templates/admin/admin_site_search.html
- portality/util.py
- portality/view/admin.py
#1175 
I should note this also includes work from #1203 , so #1203 would be easier to review first. Then this diff will shrink considerably to only include my UI work.
> Feature/1175 Bulk delete UI

- deploy/anacrontab-production-background-apps
- deploy/anacrontab-test-background-apps
- deploy/crontab-production-background-apps
- deploy/crontab-test-background-apps
- deploy/deploy-background-apps.sh
- deploy/deploy-gateway.sh
- deploy/supervisor/huey-long-running-production.conf
- deploy/supervisor/huey-long-running-test.conf
- deploy/supervisor/huey-main-production.conf
- deploy/supervisor/huey-main-test.conf
#1239 
Can only properly test whether any of this works after merging, so I'll do that, and will likely follow up with fix PRs.
Feel free to review, however, I'll try to fix anything you point out pretty promptly.
> add huey supervisor configs and a background apps deploy script

- portality/app.py
- portality/static/doaj/js/available_facetviews/public.journalarticle.facetview.js
- portality/static/doaj/js/available_facetviews/public.journaltocarticles.facetview.js
- portality/static/doaj/js/facetview_results_render_callbacks.js
- portality/static/widget/fq_widget_depends_compiled.js
Hello!
The DOI foundation recommends a [new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8).
Cheers :-)
> link DOIs against preferred resolver

- doajtest/unit/test_models.py
- doajtest/unit/test_scripts_accounts_with_marketing_consent.py
- docs/system/DATA_MODELS.md
- portality/models/account.py
- portality/scripts/accounts_with_marketing_consent.py
- portality/templates/account/view.html
- portality/view/account.py
Addresses issue [#1725](https://github.com/DOAJ/doajPM/issues/1725)
> Added marketing consent feature

- docs/system/DATA_MODELS.md
I think this was just a duplication so wanted to remove it to avoid any potential confusion.
> Remove duplicate eissn line

- portality/core.py
- portality/scripts/request_es_backup.py
- portality/settings.py
- portality/tasks/check_latest_es_backup.py
- portality/tasks/consumer_main_queue.py
- portality/tasks/request_es_backup.py
- requirements.txt
This moves the cron task to make an ES backup into the background tasks workflow.
> Es backup bg task

- portality/app.py
- portality/settings.py
- portality/view/status.py
- production.cfg
Hello @Steven-Eardley please review this PR of the status endpoint into develop
> Status endpoint

- portality/templates/doaj/article.html
fixes: https://github.com/DOAJ/doajPM/issues/1579
closes: https://github.com/DOAJ/doaj/pull/1651
> add doi metadata to article

- doajtest/unit/test_models.py
- portality/formcontext/forms.py
- portality/formcontext/xwalk.py
- portality/models/bibjson.py
#Fixes: https://github.com/DOAJ/doajPM/issues/2056
The information in the form is added, keywords are changed to lowercase before saving into bibjson struct.
> Change keywords to lowercase before submitting to DOAJ

- portality/templates/doaj/index.html
See https://github.com/DOAJ/doajPM/issues/2481
> Small homepage adjustments

- portality/templates/application_form/_application_diff.html
> filter application_status from diff table

- portality/templates/application_form/publisher_update_request.html
- portality/templates/formcontext/publisher_update_request.html
> Update UR copy

- portality/templates/doaj/toc.html
> Explicitly state when there is no waiver policy

- portality/static/doaj/css/application_form.css
- portality/static/js/application_form.js
- portality/templates/application_form/02-about/index.html
- portality/templates/application_form/03-copyright-licensing/index.html
- portality/templates/application_form/04-editorial/index.html
- portality/templates/application_form/05-business-model/index.html
- portality/templates/application_form/06-best-practice/index.html
- portality/templates/application_form/07-review/index.html
- portality/templates/application_form/_buttons.html
- portality/templates/application_form/public_application.html
See DOAJ/doajPM#2486, comment https://github.com/DOAJ/doajPM/issues/2486#issuecomment-703701032
> Feature/2486 Add back link

- portality/templates/doaj/toc.html
Make sure 'no waiver' doesn’t get displayed for journals w/out APCs or other charges
Close DOAJ/doajPM#2612
> Update no waiver policy message

- portality/view/doaj.py
- static_content/_support/content/thank-you.md
> Add static thank you for support page

- portality/templates/includes/header.html
Better semantically, also reduces spacing
DOAJ/doajPM#2685
> Tag flash notifs as <aside>s instead of <section>s

- doajtest/unit/test_index_searchbox.py
- portality/view/doaj.py
https://github.com/DOAJ/doajPM/issues/2398
> Redirect for legacy search

- portality/static/js/application_form.js
- portality/static/js/formulaic.js
https://github.com/DOAJ/doajPM/issues/2610
> add spaces after commas for taglists on af review page

- doajtest/unit/apiv2_tests/test_api_crud_article.py
- portality/api/v2/data_objects/article.py
https://github.com/DOAJ/doajPM/issues/2950
> remove api article keywords limitation

- portality/core.py
- portality/lib/formulaic.py
- portality/templates/application_form/_application_diff.html
- portality/templates/application_form/_field.html
- portality/templates/application_form/_list.html
- portality/templates/application_form/_value.html
Issue: https://github.com/DOAJ/doajPM/issues/2824
Issue: https://github.com/DOAJ/doajPM/issues/2761
Issue: https://github.com/DOAJ/doajPM/issues/2820 (the same commit as for #2824)
> Changes to diff table

- portality/settings.py
Added a role 'cloockss' for the user to enable clockss feature
> Added 'clockss' role

- doajtest/unit/test_models.py
- portality/models/__init__.py
- portality/models/preservation.py
Created intial model for preservation
> Initial commit for preservation model

- portality/forms/application_forms.py
- portality/templates/application_form/_application_diff.html
for https://github.com/DOAJ/doajPM/issues/3012#issuecomment-882129772
Layout as discussed in the issue.
> add diff_table_context s to the application forms, propose the layout

- doajtest/mocks/preservation.py
- doajtest/unit/test_task_preservation.py
- portality/settings.py
- portality/tasks/preservation.py
- setup.py
Implemented functions to upload preservation files
> Second round of merge - Feature/clockss upload

- portality/forms/article_forms.py
- portality/forms/validate.py
https://github.com/DOAJ/doajPM/issues/3030
> Prevent submitting 2 identical issns via metadata form without the error

- portality/migrate/2819_clean_unused_license_data/migrate.json
- portality/migrate/2819_clean_unused_license_data/operations.py
Script for:  https://github.com/DOAJ/doajPM/issues/2819
Needs to be run before: https://github.com/DOAJ/doaj/pull/1946
> Cleanup licenses in article records - script

- portality/tasks/preservation.py
Fixed issue checking the owner of article which throws error
> Fixed issue checking owner of article

- portality/templates/admin/admin_site_search.html
- portality/templates/admin/applications.html
See DOAJ/doajPM#2207
See DOAJ/doajPM#2688
> Inlined bulk edit form fields

- cms/data/nav.yml
- cms/pages/apply/copyright-and-licensing.md
- portality/view/doaj.py
> Add copyright licensing page

- portality/migrate/2819_clean_unused_license_data/migrate.json
- portality/upgrade.py
I have tested and the licenses are getting removed from journal.
Also the license under article is getting removed. If it is expected behavior than it should be fine. Otherwise it can be fixed.
This is happening when the article object is created
> Updated script to remove licenses from article

- cms/sass/components/_form.scss
- cms/sass/components/_modal.scss
- cms/sass/layout/_editorial-panel.scss
- cms/sass/pages/_apply.scss
- portality/static/js/formulaic.js
- portality/templates/application_form/_group.html
- portality/templates/application_form/_list.html
- portality/templates/application_form/assed_application.html
- portality/templates/application_form/assed_journal.html
- portality/templates/application_form/editor_application.html
- portality/templates/application_form/editor_journal.html
- portality/templates/application_form/maned_application.html
- portality/templates/application_form/maned_journal.html
This is the conjunction of issues https://github.com/DOAJ/doajPM/issues/2904 and https://github.com/DOAJ/doajPM/issues/3136,
based on and supersedes the pull requests https://github.com/DOAJ/doaj/pull/2040 and https://github.com/DOAJ/doaj/pull/2017
> Feature/2022 01 27 feature/3136 2904 textareas view note link

- cms/sass/base/_general.scss
- cms/sass/base/_utils.scss
- cms/sass/layout/_nav-bar.scss
- cms/sass/layout/_primary-nav.scss
- cms/sass/layout/_secondary-nav.scss
- cms/sass/themes/_dashboard.scss
- portality/bll/services/todo.py
- portality/settings.py
- portality/templates/account/login.html
- portality/templates/admin/admin_base.html
- portality/templates/application_form/editorial_form_body.html
- portality/templates/application_form/maned_application.html
- portality/templates/application_form/maned_journal.html
- portality/templates/dashboard/index.html
- portality/templates/includes/header.html
- portality/templates/layouts/dashboard_base.html
- portality/templates/unlocked.html
- portality/view/account.py
- portality/view/dashboard.py
> Adjust maned UI

- cms/sass/base/_general.scss
- cms/sass/base/_utils.scss
- cms/sass/components/_alert.scss
- cms/sass/components/_buttons.scss
- cms/sass/components/_form.scss
- cms/sass/components/_tag.scss
- cms/sass/themes/_dashboard.scss
- portality/settings.py
- portality/static/js/edges/admin.editor_groups.edge.js
- portality/static/js/edges/admin.users.edge.js
- portality/templates/account/_edit_user_form.html
- portality/templates/account/view.html
- portality/templates/admin/editor_group.html
- portality/templates/dashboard/index.html
- portality/templates/dashboard/nav.html
- portality/templates/includes/header.html
- portality/templates/layouts/dashboard_base.html
> Post-monitored-testing fixes

- cms/data/notifications.yml
- doajtest/unit/event_consumers/test_application_publisher_accepted_notify.py
- doajtest/unit/event_consumers/test_update_request_publisher_accepted_notify.py
- portality/bll/services/events.py
- portality/events/consumers/application_publisher_accepted_notify.py
- portality/events/consumers/application_publisher_created_notify.py
- portality/events/consumers/update_request_publisher_accepted_notify.py
Changing "owner" to "publisher" in the notification system.
> refactoring

- portality/settings.py
- portality/view/account.py
For https://github.com/DOAJ/doajPM/issues/3279
> redirect user to page suitable to their role type after login

- portality/migrate/20220323_3256_enforce_correct_es_type_in_articles/migrate.json
- portality/migrate/20220323_3256_enforce_correct_es_type_in_articles/operations.py
Script for https://github.com/DOAJ/doajPM/issues/3256. Operations where needed. Tested locally.
> add operations to rewrite es type when needed

- portality/api/current/bulk/articles.py
- portality/bll/services/article.py
for [Produce a more helpful error message for unhandled exception re attempt to change URL or DOI #3224](https://github.com/DOAJ/doajPM/issues/3224)
* for /api/bulk/articles, all exception `DuplicateArticleException` will be show as 403 with json format instead of html format
```
{"status": "forbidden", "error": "DOI or Fulltext URL have been changed.  This operation is not permitted, please contact an administrator for help. (ref: f525757c-d854-11ec-8dab-97521b9201b9)"}
```
```
curl --location --request POST 'http://localhost:5004/api/bulk/articles?api_key=a5b03fb3d0084123aab6859193cfe5e6' \
--header 'Content-Type: application/json' \
--data-raw '[
{
"bibjson": {
"abstract": "This paper discusses and studies the composition and characteristics of biospeckle on the surface of bone …
```
> 3224 -- change exception type for response body as json

- cms/data/notifications.yml
> Clean up typography, punctuation and capitalisation in email notifications

- cms/sass/components/_progress-bar.scss
- cms/sass/components/_tag.scss
- cms/sass/main.scss
- portality/static/js/dashboard.js
- portality/templates/dashboard/index.html
> Style editorial status section

- portality/templates/admin/editor_group.html
For: https://github.com/DOAJ/doajPM/issues/3293
allow clear for maned in group forms.
> allow clear for editor and manager editor in the group form

- cms/sass/components/_dropdown.scss
- cms/sass/components/_notifications.scss
- cms/sass/main.scss
- cms/sass/themes/_dashboard.scss
- portality/static/js/edges/notifications.edge.js
- portality/static/js/notifications.js
- portality/templates/layouts/dashboard_base.html
See DOAJ/doajPM#3282 and DOAJ/doajPM#3283
> Style notifications

- doajtest/functional/oaipmh_client_test.py
For: https://github.com/DOAJ/doajPM/issues/3345
Some basic improvements to the oai-pmh test client to make it easier to adjust harvesting parameters.
This PR...
There are no human tests to run for this feature, but if you want to run this test against a running DOAJ instance you can use
```
python doajtest/functional/oaipmh_client_test.py
```
This is set to automatically harvest all journals and all articles (in both metadata formats) from a localhost instance of DOAJ.  If you want to change that, you need to edit the file and modify the `RUN_CONFIGURATION` variable to specify only the harvests you want to run.
None.  This code can be merged at any point, and does not need its own deploy to live at the time, as it is only …
> improve the test client to make it easier to adjust oai-pmh testing

- doajtest/unit/application_processors/test_application_processor_emails.py
- doajtest/unit/test_lib_plausible.py
See # https://github.com/DOAJ/doajPM/issues/3353
* Fix some test cases which fail with python3.7 + pytest
* Codeship could be still fail in the future, because there have some testcases is unstable (sometime success, but sometime fail)
This PR...
1. ...
2. ...
What deployment considerations are there? (delete any sections you don't need)
What configuration changes are included in this PR, and do we need to set specific values for production
What scripts need to be run from the PR (e.g. if this is a report generating feature), and when (once, regularly, …
> add log for debugging

- portality/static/crossref/JATS-journalpublishing1.xsd
- portality/static/crossref/common4.4.2.xsd
- portality/static/crossref/common5.3.1.xsd
- portality/static/crossref/crossref4.4.2.xsd
- portality/static/crossref/crossref5.3.1.xsd
- portality/static/crossref/mathml3-common.xsd
- portality/static/crossref/mathml3-content.xsd
- portality/static/crossref/mathml3-presentation.xsd
- portality/static/crossref/mathml3-strict-content.xsd
- portality/static/crossref/mathml3.xsd
See https://github.com/DOAJ/doajPM/issues/3366
The MathML XSD has ceased to be resolvable at its external location, so we have localised it to load it direct from doaj.org in future
This PR...
Starting the app should be sufficient to see if this has worked.
What deployment considerations are there? (delete any sections you don't need)
XSDs must be served as HTTP, and not at HTTPS
> localise mathml so it can be resolved from doaj.org

- doajtest/testbook/dashboards/editorial_group_status.yml
- portality/app.py
- portality/static/js/dashboard.js
- portality/templates/dashboard/index.html
- portality/templates/editor/dashboard.html
- portality/templates/layouts/dashboard_base.html
- portality/view/doajservices.py
- portality/view/editor.py
Add badger feature to editorial dashboard (making sure it is not shown to associate editors
[See #3235](https://github.com/DOAJ/doajPM/issues/3235)
Described [here](https://github.com/DOAJ/doajPM/issues/3235#issuecomment-1271558591) and implemented accordingly.
Additional implementation includes hiding the admin dashboard link from non-admin users.
This PR...
List the Functional Tests that must be run to confirm this feature.
https://docs.google.com/spreadsheets/d/1hOkzOP8kTKi0sDkQmZ7WNyMaWG8btzmiTo8kaED8FFQ/edit#gid=0
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
> Editorial Group Status on dashboard

- dependencies.py
- dependencies.sh
See: https://github.com/DOAJ/doajPM/issues/3325
This PR contains the scripts for dependencies analysis. To run make sure the dependencies.sh is executable and run the dependencies.py script. The script result is saved in dependencies.json and dependencies.csv in the root of the project.
The csv  result of the script run on fresh dev environment is attached.
[dependencies.csv](https://github.com/DOAJ/doaj/files/9901911/dependencies.csv)
> python and shell scripts for dependencies analysis

- portality/forms/article_forms.py
Provide an empty string as a default publication month in the article metadata upload form.
[See #3423](https://github.com/DOAJ/doajPM/issues/3423)
This PR adds empty string as a default publication month in the article metadata upload form. The rest of the system already accommodates an empty string as a value (ignores it as "no data").
This PR...
Article Metadata Upload Form
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
**N/A**
> Provide an empty string as a default publication month in the article metadata upload form.

- portality/templates/layouts/dashboard_base.html
https://github.com/DOAJ/doajPM/issues/3422#issuecomment-1385499419
> spell out the roles

- portality/templates/dashboard/_todo.html
https://github.com/DOAJ/doajPM/issues/3422#issuecomment-1385594430
> change the cards' text action

- portality/lib/plausible.py
- portality/settings.py
- portality/templates/_js_includes.html
See #
* https://github.com/DOAJ/doajPM/issues/3456#issuecomment-1429604659
* fix counting of unique visitor
* ***Remember to change value of environment variable*** `PLAUSIBLE_JS_URL` to `/js/script.outbound-links.file-downloads.js` in production.
This PR...
1. ...
2. ...
What deployment considerations are there? (delete any sections you don't need)
What configuration changes are included in this PR, and do we need to set specific values for production
What scripts need to be run …
> fix counting on unique visitor

- cms/data/nav.yml
- cms/pages/about/at-20.md
- portality/view/doaj.py
See DOAJ/doajPM#3512
Simply adds a blank page for DOAJ @ 20 to be merged to `static_pages` for now. 
This PR...
1. ...
2. ...
What deployment considerations are there? (delete any sections you don't need)
What configuration changes are included in this PR, and do we need to set specific values for production
What scripts need to be run from the PR (e.g. if this is a report generating feature), and when (once, regularly, etc).
What migrations need to be run to deploy this
What additional monitoring is required of the application as a result of this feature
What new infrastructure does this PR require (e.g. new services that need to run on the back-end).
What CI changes are required for this
> Add DOAJ at 20

- doajtest/testbook/articles_preservation/user_test_script.yml
- portality/settings.py
- portality/templates/publisher/readonly.html
- portality/view/publisher.py
See # https://github.com/DOAJ/doajPM/issues/3424
This PR...
- …
> Hot fix to put preservation tab under maintenance

- portality/scripts/history_archive.py
Check for empty files before doing json load to avoid exception
See https://github.com/DOAJ/doajPM/issues/2265
This PR...
* For multiple reviewers, feel free to add your own checkbox with your …
> Check for empty files

- portality/settings.py
- portality/ui/debug_toolbar.py
See # 
* https://github.com/DOAJ/doajPM/issues/3577
This PR... …
> turn off config module

- portality/scripts/journal_urls.py
Updated the script not to escape the html content
See # https://github.com/DOAJ/doajPM/issues/3600
This PR...
* For multiple reviewers, feel free to add your own checkbox with your github username …
> Link Checker script

- portality/settings.py
- portality/view/doaj.py
See #
* https://github.com/DOAJ/doajPM/issues/3576
This PR...
- …
> add new plausible event `PublicDataDump`

- portality/scripts/application_status_report.py
See https://github.com/DOAJ/doajPM/issues/3568
Run application_status_report.py script to generate csv file
ex: python portaity/scripts/application_status_report.py -y <year> -o <output file full path>
This PR...
* For each checklist item that has been confirmed by the Developer, check the Reviewer …
> new script to generate report for number of applications per year

- portality/scripts/applications_rejected_data.py
See https://github.com/DOAJ/doajPM/issues/3685
This PR...
- No …
> Rejected applications

- portality/scripts/manage_background_jobs.py
See # <- enter link to issue on main board
This PR...
- No …
> implement ability to process jobs directly on the command line

- portality/forms/application_forms.py
[See #3055](https://github.com/DOAJ/doajPM/issues/3055)
This PR...
* For multiple reviewers, feel free to add your own checkbox with your github username next to it if that helps with review …
> Add click-to-copy and full-contents widgets to Continuation Information

- portality/settings.py
See #
* https://github.com/DOAJ/doajPM/issues/3874
This PR...
- …
> 3874 upgrade epmc version

- portality/bll/services/application.py
* Issue: https://github.com/DOAJ/doajPM/issues/3967
---
A user has been able to trigger a bug in the csv validator which we are unable to reproduce.  Following the stack trace it looks like  a cast to string is required explicitly at serialisation, so this code introduces that cast in the hopes of fixing the user's error.
This PR...
*Developers should review and confirm each of these items before requesting review*
- No deprecated methods are used
- No magic strings/numbers - all strings are in `constants` or `messages` files
- ES queries are wrapped in a Query object rather than inlined in the code
- Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
- Cleaned up commented out code, etc
- Urls are constructed with `url_for` not hard-coded
- …
> add explicit cast to string for error messages

- portality/forms/application_forms.py
* Issue: https://github.com/DOAJ/doajPM/issues/3969
*briefly describe the PR here*
This PR...
*Developers should review and confirm each of these items before requesting review*
- No deprecated methods are used
- No magic strings/numbers - all strings are in `constants` or `messages` files
- ES queries are wrapped in a Query object rather than inlined in the code
- Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
- Cleaned up commented out code, etc
- Urls are constructed with `url_for` not hard-coded
- Core model documentation has been added to if needed: https://docs.google.com/spreadsheets/d/1lun2S9vwGbyfy3WjIjgXBm05D-3wWDZ4bp8xiIYfImM/edit
- Events and consumers documentation has been added if needed: …
> add short help to continuation fields

- portality/static/js/edges/admin.users.edge.js
* Issue: [4075](https://github.com/DOAJ/doajPM/issues/4075)
---
*briefly describe the PR here*
This PR...
*Developers should review and confirm each of these items before requesting review*
- No deprecated methods are used
- No magic strings/numbers - all strings are in `constants` or `messages` files
- ES queries are wrapped in a Query object rather than inlined in the code
- Where possible our common library functions have been used (e.g. dates manipulated via `dates`)
- Cleaned up commented out code, etc
- Urls are constructed with `url_for` not hard-coded
- Core model documentation has been added to if needed: https://docs.google.com/spreadsheets/d/1lun2S9vwGbyfy3WjIjgXBm05D-3wWDZ4bp8xiIYfImM/edit
- Events and consumers documentation has been added if needed: …
> add Created Date facet to admin users search
